version: '2'
services:
    jpa-app:
        image: jpa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jpa-mysql:3306/jpa?useUnicode=true&characterEncoding=utf8&useSSL=false
            - APP_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jpa-mysql:
        extends:
            file: mysql.yml
            service: jpa-mysql
